### ISSUE TITLE
Add /players counter?

### ISSUE THREAD

**Issue by andrew207** [palmettos/D2ID#4]
Now that playersx runs are allowed this probably should be added as a feature. I tried to but the code is too complex for me to understand fully. I made my own small repo with code to read playersx, it's just a static memory location. 

https://github.com/andrew207/d2-playersx 

Hopefully this can be integrated without too much difficulty :).

**Comment by squeek502** [comment]
This would probably be better directed at [DiabloInterface](https://github.com/Zutatensuppe/DiabloInterface), which D2ID uses a forked version of.

Alternatively, you can use [d2info](https://github.com/squeek502/d2info) which does the same thing as your tool, but also outputs a .txt file (output/players-x.txt) which can be easily added as an OBS text source, and has support for more game versions ([the memory locations for each version can be found here if you want them](https://github.com/squeek502/d2info/blob/master/d2info/offsets.lua)).

**Comment by andrew207** [comment]
Noted, thanks.
